# Alacritty theme matching your Omarchy colors

colors:
  # Default colors
  primary:
    background: '0x0E131B'
    foreground: '0x9DA5B3'

  # Cursor and selection
  cursor:
    text:       '0x0E131B'   # text color under the cursor
    cursor:     '0xF77450'   # cursor color

  selection:
    text:       '0xD7DAE0'   # selected text
    background: '0x4C566A'   # selection background

  # ANSI colors
  normal:
    black:       '0x3B4252'
    red:         '0xCD2B3B'
    green:       '0x499149'
    yellow:      '0xEBCB8B'
    blue:        '0x598DEF'
    magenta:     '0xA78CFA'
    cyan:        '0x55B5D0'
    white:       '0xE5E9F0'

  bright:
    black:       '0x394761'
    red:         '0xCA3242'
    green:       '0x88CD57'
    yellow:      '0xEBCB8B'
    blue:        '0x689ED4'
    magenta:     '0xC76BB6'
    cyan:        '0x52CECC'
    white:       '0xECEFF4'

