accent = "#81a1c1"
cursor = "#f77450"
foreground = "#9DA5B3"
background = "#0E131B"
selection_foreground = "#d7dae0"
selection_background = "#4c566a"

color0 = "#3b4252"
color1 = "#cd2b3b"
color2 = "#499149"
color3 = "#ebcb8b"
color4 = "#598DEF"
color5 = "#A78CFA"
color6 = "#55b5d0"
color7 = "#e5e9f0"
color8 = "#394761"
color9 = "#ca3242"
color10 = "#88cd57"
color11 = "#ebcb8b"
color12 = "#689ed4"
color13 = "#c76bb6"
color14 = "#52cecc"
color15 = "#eceff4"
